### ISSUE TITLE
feedparser 6.0.0 breaks Mylar3 startup

### ISSUE THREAD

**Issue by OneCDOnly** [mylar3/mylar3#451]
Just a heads-up guys. Looks like `feedparser` 6.0.0 was [released today](https://pypi.org/project/feedparser/#history) and is breaking my test installs of `SABnzbd` and `Mylar3`. 😞 

A fresh clone from GitHub master branch: 
```
[/share/MD0_DATA/.qpkg/Mylar3/Mylar3] # /opt/bin/python3 Mylar.py --help
Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/share/MD0_DATA/.qpkg/Mylar3/Mylar3/mylar/__init__.py", line 38, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/share/MD0_DATA/.qpkg/Mylar3/Mylar3/mylar/rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "/share/MD0_DATA/.qpkg/Mylar3/Mylar3/mylar/rsscheck.py", line 52, in <module>
    feedparser._FeedParserMixin._start_newznab_attr = _start_newznab_attr
AttributeError: module 'feedparser' has no attribute '_FeedParserMixin'
```
Still works fine with `feedparser` 5.2.1

**Comment by evilhero** [comment]
Should be fixed in both branches as of now (v0.4.5 is the newest master release).

**Comment by OneCDOnly** [comment]
@evilhero thank you, that works great now. 👍🏽 

Cheers!
