### ISSUE TITLE
You're running an unknown version of Mylar. Update or Close

### ISSUE THREAD

**Issue by edimusxero** [mylar3/mylar3#409]
I have seen this addressed various times before but I have not yet found a solution that works for me.  Here are what the logs are telling me.

> 2020-08-11` 13:29:40 | DEBUG | [ERROR] Unable to retrieve git revision history for some reason: 'NoneType' object has no attribute 'stdout'
2020-08-11 13:29:40 | ERROR | Command  git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5  didn't work [__init__() got an unexpected keyword argument 'text']
2020-08-11 13:29:40 | DEBUG | Trying to execute: git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 with shell in /usr/local/src/mylar3
2020-08-11 13:29:40 | ERROR | Command  /usr/bin/git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s"  -n 5 didn't work [__init__() got an unexpected keyword argument 'text']

and my config.ini looks like this

> [Git]
git_user = mylar3
check_github = True
git_path = /usr/bin/git
check_github_on_startup = True
git_branch = master

any help would be greatly appreciated

**Comment by barbequesauce** [comment]
Please generate a care package (button on the top of the config page) and attach it here.

**Comment by edimusxero** [comment]
This is what I get when I try to create a care package:

> 500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/src/mylar3/venv/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/src/mylar3/venv/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/src/mylar3/venv/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/src/mylar3/venv/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/src/mylar3/mylar/webserve.py", line 5780, in carepackage
    cp = carePackage()
  File "/usr/local/src/mylar3/mylar/carepackage.py", line 85, in __init__
    self.environment()
  File "/usr/local/src/mylar3/mylar/carepackage.py", line 101, in environment
    text=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

**Comment by evilhero** [comment]
As per our readme, mylar3 will only work with python versions above 3.7. 2 - you're running 3.6.x from the looks of it.

**Comment by edimusxero** [comment]
ah, ok let me try to update python

**Comment by edimusxero** [comment]
that seems to have fixed everything, thanks

**Comment by barbequesauce** [comment]
We good to close?

**Comment by edimusxero** [comment]
yes, looks good.  Thanks

**Comment by TupaNegreiros** [comment]
Same here, I've just upgrade from Mylar/python2.
Running Python Version : 3.7.3
I've kept config.ini, datadir, changed log_dir in config.ini

After changed, in config.ini, git_user from **evilhero** to **mylar3**, problem solved.
